// import type { Metadata } from "next";
// import { ThemeProvider } from "@/components/theme-provider"
// import { Inter } from "next/font/google";
// import "./globals.css";



// const inter = Inter({
//   subsets: ["vietnamese"],
// });

// export const metadata: Metadata = {
//   title: "Smart-Market-AI",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en" suppressHydrationWarning>
//       <body
//         className={`${inter.className} ${inter.className} antialiased`}
//       >
//         <ThemeProvider
//             attribute="class"
//             defaultTheme="system"
//             enableSystem
//             disableTransitionOnChange
//           >
//             {/* <ModeToggle/> */}
//             {children}
//           </ThemeProvider>
//       </body>
//     </html>
//   );
// }


import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Sidebar from "@/app/landingpage/components/SideBar/Sidebar";

const inter = Inter({
  subsets: ["vietnamese"],
});

export const metadata: Metadata = {
  title: "Smart Market AI",
  description: "Hệ thống quản lý chợ dân sinh thông minh",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="vi" suppressHydrationWarning>
      <body className={`${inter.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div style={{ display: "flex", minHeight: "100vh" }}>
            {/* <Sidebar /> */}
            <main style={{ flex: 1, padding: "20px" }}>{children}</main>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
